name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: esphome/build-action/.github/workflows/build.yml@main
    with:
      files: temperature-monitor-esp32.yaml,temperature-monitor-esp8266.yaml
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
