name: Publish

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      version:
        description: 'The version of the firmware to build'
        required: true
  release:
    types: [published]

jobs:
  build:
    name: Build Firmware
    uses: esphome/workflows/.github/workflows/build.yml@main
    with:
      files: |
        project-template-esp32.factory.yaml
        project-template-esp32-c3.factory.yaml
        project-template-esp32-s3.factory.yaml
      esphome-version: 2024.7.3
      combined-name: project-template
      release-summary: ${{ github.event_name == 'release' && github.event.release.body || '' }}
      release-url: ${{ github.event_name == 'release' && github.event.release.html_url || '' }}
      release-version: ${{ (github.event_name == 'release' && github.event.release.tag_name) || (github.event_name == 'workflow_dispatch' && inputs.version) || '' }}

  publish:
    name: Publish to GitHub Pages
    if: github.event_name == 'release' || (github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main')
    runs-on: ubuntu-latest
    needs: [build]
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: actions/download-artifact@v4.1.8
        with:
          path: files

      - name: Build
        uses: actions/jekyll-build-pages@v1.0.13
        with:
          source: ./static
          destination: ./output

      - name: Copy firmware and manifest
        run: cp -r files/${{ needs.build.outputs.version }}/* output/

      - uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: output
          retention-days: 1

      - name: Setup Pages
        uses: actions/configure-pages@v5.0.0

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.5
